project:
  type: website

website:
  title: "Hugo Machado"  
  page-footer:
    left: "©2026, Hugo Machado"
    right: "Built with [Quarto](https://quarto.org/)."
  navbar:
    title: "Hugo Machado"
    background: white
    foreground: dark
    search: false

format:
  html:
    theme: minty
    toc: false
    page-layout: article