---
title: ""
---

## Pesquisa

Estudo como processos culturais, psicológicos e institucionais moldam a forma como as pessoas organizam suas crenças políticas e como essas crenças orientam o comportamento político em diferentes contextos. Meu trabalho articula comportamento político, sociologia cultural e política comparada para entender não apenas o que as pessoas pensam, mas como elas estruturam e processam suas ideias políticas. Para uma descrição mais detalhada da minha pesquisa, por favor, consulte a aba do meu CV. 

Também colaboro em projetos que examinam: 

  - A mobilização e a mensuração de crenças conspiratórias em diferentes países 
  - Os fundamentos emocionais e fisiológicos do preconceito e da intolerância política 
  - Como as discussões políticas cotidianas moldam a avaliação e a interação social 

### Projeto de Tese

Minha tese investiga como os significados culturais e os ambientes informacionais moldam as identidades e as estruturas de crenças políticas nas democracias contemporâneas. Utilizo *surveys* e experimentos para explorar como certas crenças políticas e marcadores culturais se aglutinam, e como influenciam as atitudes e a participação política. Atualmente, desenvolvo esta pesquisa sob a orientação do Prof. Mathieu Turgeon.